# Configuration file of the Baron

# Amount of Transposition Hashtables in MB
mainhash 200

# Learning, on by default
# Allowed values: on/off
# Recommended value: on
learning on

# Name and location of the opening book
# A total of 16 books in baron and polyglot format can be used. The books will be probed 
# in the order of their listing here.
#   bookfile: Book in Baron format
#   bookpoly: Book in Polyglot format
#   bookclient: Accessing remote boot on Baron's book server (will require additional license in the future)
# Also 1 book in CTG format can be specified. The CTG book is always probed first. A future 
# enhancement is that multiple CTG books can be used and mixed with other formats, but currently
# that is not possible. 
#bookclient thebaron.ddns.net:4463
#bookfile d:/baron/books/big
#bookpoly d:/baron/books/general.bin
#bookctg d:/baron/books/baron.ctg

# Whether nullmove is used or not
# Allowed values: on/off
# Default/Recommended: on
# nullbase: number of quarterplies used for nullmove reduction
# nullprogress: measure of progressive nullmove reduction based on depth (more reduction for deeper searches)
#donullmove on
#nullbase 12
#nullprogress 6

# Internal Iterative Deepening.
# Allowed values: on/off
# Default/Recommended: on
#doiid on

# Singular extensions
# Extension parameters specified in quarter plies
# Default/Recommended values:
# singular on
# singreduction 4
# singmargin 100
#singular on
#singmargin 100
#singextension 4

# LMR
# Specified in quarter plies
# Default/Recommended values:
# lmrpv 0
# lmrscout 4
# lmrextrapv 6
# lmrextrascout 2
#lmrpv 0
#lmrscout 4
#lmrextrapv 6
#lmrextrascout 2

# Razoring
# Specified in full plies
#prunelevel 5
#prunepv off
#prunesecure 100

# The next settings are only meant for test/tuning purposes. For 'regular' use the parameter 'prunesecure' should be used instead.
# prunealphamargin <depthleft> <percentage of default> specifies the amount the quiescent value should be below alpha so that the
# quiescent score+margin will be returned by the search instead of searching it to depthleft
# prunebetamargin <depthleft> <percentage of default> specifies the amount the quiescent value should be above beta so that the
# quiescent score-margin will be returned by the search instead of searching it to depthleft
#prunealphamargin 1 100
#prunebetamargin 1 100
#prunealphamargin 2 100
#prunebetamargin 2 100
#prunealphamargin 3 100
#prunebetamargin 3 100
#prunealphamargin 4 100
#prunebetamargin 4 100
#prunealphamargin 5 100
#prunebetamargin 5 100
#prunealphamargin 6 100
#prunebetamargin 6 100
#prunealphamargin 7 100
#prunebetamargin 7 100
#prunealphamargin 8 100
#prunebetamargin 8 100

# King Safety Evaluation
# kingsafety scores the attack against the king (offensive)
# kingshield scores the shield in front of the king (defensive)
# Percentage of the default scoring method
#kingsafety 100
#kingshield 100

# Multi processor configuration:
# cpus: Number of CPU's used (max 16 or the number of processors in your system, whatever is the lower number)
# splitdepth: number of quarter-plies that needs to be remaining to attempt to split the search.
# minsplit: number of remaining moves in a position to attempt creating a splitpoint (at least 2)
# maxsplit: maximum number of threads that may be assigned to a splitpoint (default: all)
# gluecores: 'Glue' the workers to a specific cpu core (only set to 'on' when the Baron has exclusive use of the machine)
#cpus 1
#splitdepth 12
#minsplit 2
#maxsplit 12
#gluecores off

# Keep the noise level down
#postoutput 1

# Some more options
# timeuse: Percentage of default amount of time allocated to make a move
# easymove: Reply faster when there is one obvious good move
# logging: Turns on/off the logfile (has the name of this configuration file with the extension .log)
# priolow: Sets the engine to run at lower priority to improve responsiveness of the system
# ucioption (UCI): Allows setting options through UCI option commands. Setting it to off will still advertise the options,
#                  but the engine will ignore the commands. Values from this file will be used for all.
# icsmode (WB): allows the engine to select between icsmode (which will kibitz/whisper information). Values are 'on', 'off' and 'smart'
#               When set to 'smart' the engine will determine ics mode based on the winboard ics command.
#timeuse 100
#easymove on
logging off
priolow off
#ucioption on
#icsmode smart

# Syzygy Base options
# syzygypath: path to where the sygyzybases are located. 
# szqsearch: Turns probing on/off in quiescense search. Only turn on with bases on SSD or flashdisk
# szdepth: Minimum remaining depth in quarterplies to probe the bases. Must be 0 to probe in qsearch
#syzygypath i:/wdl;i:/dtz
#szqsearch off
#szdepth 8
